/**
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */



#include <rtac_asio/StreamWriter.h>

using namespace std::placeholders;

namespace rtac { namespace asio {

StreamWriter::StreamWriter(StreamInterface::Ptr stream) :
    stream_(stream),
    writeCounter_(0),
    writeId_(0),
    timer_(stream_->service()->service())
{}

StreamWriter::~StreamWriter()
{
    this->disable_dump();
}

StreamWriter::Ptr StreamWriter::Create(StreamInterface::Ptr stream)
{
    return Ptr(new StreamWriter(stream));
}

void StreamWriter::flush()
{
    stream_->flush();
}

void StreamWriter::reset()
{
    stream_->reset();
}

void StreamWriter::enable_dump(const std::string& filename, bool appendMode)
{
    if(txDump_.is_open()) {
        std::cerr << "tx dump already enabled. Close before reopen." << std::endl;
        return;
    }
    
    auto mode = std::ofstream::out;
    if(appendMode) {
        mode = std::ofstream::app;
    }
    txDump_.open(filename, mode);
    if(!txDump_.is_open()) {
        std::cerr << "rtac_asio : Could not open file "
                  << filename << " for writing." << std::endl;
    }
}

void StreamWriter::disable_dump()
{
    if(txDump_.is_open()) {
        txDump_.close();
    }
}

void StreamWriter::dump_callback(Callback callback, const uint8_t* data,
                                 const ErrorCode& err, std::size_t writtenCount)
{
    if(!err && this->dump_enabled()) {
        for(std::size_t i = 0; i < writtenCount; i++) {
            txDump_ << data[i];
        }
        txDump_.flush();
    }
    callback(err, writtenCount);
}

bool StreamWriter::new_write(std::size_t requestedSize, const uint8_t* data,
                             Callback callback, unsigned int timeoutMillis)
{
    std::lock_guard<std::mutex> lock(writeMutex_);
    if(writeId_ != 0) {
        // device busy
        return false;
    }
    
    writeCounter_++;
    writeId_        = writeCounter_;
    requestedSize_ = requestedSize;
    processed_     = 0;
    src_           = data;
    callback_      = callback;

    if(timeoutMillis > 0) {
        timer_.expires_from_now(Millis(timeoutMillis));
        timer_.async_wait(std::bind(&StreamWriter::timeout_reached, this, writeId_, _1));
    }

    return true;
}

void StreamWriter::finish_write(const ErrorCode& err)
{
    std::lock_guard<std::mutex> lock(writeMutex_);
    if(writeId_ == 0) {
        // No write to end (should not happend)
        return;
    }
    writeId_ = 0;
    // This calls the user callback in an executor loop (avoid potential
    // deadlock with the writeMutex_if the user callback asks for another write).
    stream_->service()->post(std::bind(callback_, err, processed_));
    // from this moment, requestedSize_, processed_, src_ and callback_ are
    // devalidated and available for a new write.
}

/**
 * Checks if the writeId associated with the caller checks out with the current
 * one saved in the writeId_ attribute.
 *
 * This allows to potentially detect callbacks which are no longer relevant.
 * (For example a write callback might be called after a timeout alwritey
 * happened. This callback needs either to generate an error or to be ignored).
 */
bool StreamWriter::writeid_ok(unsigned int writeId) const
{
    std::lock_guard<std::mutex> lock(writeMutex_);
    return writeId == writeId_;
}

void StreamWriter::timeout_reached(unsigned int writeId, const ErrorCode& /*err*/)
{
    if(!writeid_ok(writeId)) {
        return;
    }
    // If timeout was reached, a waiter might have been set
    waiterNotified_ = true;
    waiter_.notify_all();
    this->finish_write(ErrorCode()); // error should be timeout but could not
                                     // find how to make one.
}

void StreamWriter::do_write_some(std::size_t count,
                                 const uint8_t* data, Callback callback)
{
    if(!this->dump_enabled()) {
        stream_->async_write_some(count, data, callback);
    }
    else {
        stream_->async_write_some(count, data,
            std::bind(&StreamWriter::dump_callback, this,
                      callback, data, _1, _2));
    }
}

bool StreamWriter::async_write_some(std::size_t count, const uint8_t* data,
                                    Callback callback, unsigned int timeoutMillis)
{
    if(!this->new_write(count, data, callback, timeoutMillis)) {
        return false;
    }

    this->do_write_some(requestedSize_, src_,
        std::bind(&StreamWriter::async_write_some_continue, this, writeId_, _1, _2));

    return true;
}

void StreamWriter::async_write_some_continue(unsigned int writeId,
                                             const ErrorCode& err,
                                             std::size_t writtenCount)
{
    if(!writeid_ok(writeId)) {
        return;
    }
    processed_ = writtenCount;
    this->finish_write(err);
}

bool StreamWriter::async_write(std::size_t count, const uint8_t* data,
                               Callback callback, unsigned int timeoutMillis)
{
    if(!this->new_write(count, data, callback, timeoutMillis)) {
        return false;
    }

    this->do_write_some(requestedSize_, src_,
        std::bind(&StreamWriter::async_write_continue, this, writeId_, _1, _2));

    return true;
}

void StreamWriter::async_write_continue(unsigned int writeId,
                                        const ErrorCode& err,
                                        std::size_t writtenCount)
{
    if(!writeid_ok(writeId)) {
        // probably a timeout was reached
        return;
    }

    processed_ += writtenCount;
    if(!err && processed_ < requestedSize_) {
        this->do_write_some(requestedSize_ - processed_, src_ + processed_,
            std::bind(&StreamWriter::async_write_continue, this, writeId, _1, _2));
    }
    else {
        this->finish_write(err);
    }
}

std::size_t StreamWriter::write(std::size_t count, const uint8_t* data,
                                unsigned int timeoutMillis)
{
    std::unique_lock<std::mutex> lock(mutex_); // will release mutex when out of scope

    if(!this->async_write(count, data,
                          std::bind(&StreamWriter::write_callback, this, _1, _2),
                          timeoutMillis))
    {
        // device probably busy
        return 0;
    }

    waiterNotified_ = false; // this protects against spurious wakeups.
    waiter_.wait(lock, [&]{ return waiterNotified_; });

    return processed_;
}

void StreamWriter::write_callback(const ErrorCode& /*err*/, std::size_t /*writtenCount*/)
{
    // This lock prevents a deadlock in StreamWriter::write. It is possible
    // this callback is called before waiter_ started to wait. If it is the
    // case, the waiter is notified before it started to wait and will never be
    // notified in the future.
    std::unique_lock<std::mutex> lock(mutex_);

    // finish write was already called through the async_write primitive
    waiterNotified_ = true;
    waiter_.notify_all();
}

} //namespace asio
} //namespace rtac


